version: "3.7"
services:
  webapp:
    build:
      args:
        user: devpardy
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: devpardy
    container_name: devpardy-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - devpardy

  db:
    image: mysql:8
    container_name: devpardy-db
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3309:${DB_PORT}
    networks:
      - devpardy

  nginx:
    image: nginx:1.17-alpine
    container_name: devpardy-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - devpardy

networks:
  devpardy:
    driver: bridge
